//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibramePlayer.WpfApp {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InternalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibramePlayer.WpfApp.InternalResources", typeof(InternalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Edit list 的本地化字符串。
        /// </summary>
        public static string EditListCaption {
            get {
                return ResourceManager.GetString("EditListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right-click and select the media you want to operate! 的本地化字符串。
        /// </summary>
        public static string EditListMouseRightClick {
            get {
                return ResourceManager.GetString("EditListMouseRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load playlist 的本地化字符串。
        /// </summary>
        public static string LoadPlaylist {
            get {
                return ResourceManager.GetString("LoadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looping 的本地化字符串。
        /// </summary>
        public static string LoopingState {
            get {
                return ResourceManager.GetString("LoopingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media &apos;{0}&apos; loaded. 的本地化字符串。
        /// </summary>
        public static string MediaLoadedTextFormat {
            get {
                return ResourceManager.GetString("MediaLoadedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove media 的本地化字符串。
        /// </summary>
        public static string MediaRemovedCaption {
            get {
                return ResourceManager.GetString("MediaRemovedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media &apos;{0}&apos; removed. 的本地化字符串。
        /// </summary>
        public static string MediaRemovedFormat {
            get {
                return ResourceManager.GetString("MediaRemovedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove media &apos;{0}&apos; from List? 的本地化字符串。
        /// </summary>
        public static string MediaRemovedTextFormat {
            get {
                return ResourceManager.GetString("MediaRemovedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string MenuRemoved {
            get {
                return ResourceManager.GetString("MenuRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported media extension &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string NotSupportedMediaExtensionFormat {
            get {
                return ResourceManager.GetString("NotSupportedMediaExtensionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End time 的本地化字符串。
        /// </summary>
        public static string PlaylistEndTime {
            get {
                return ResourceManager.GetString("PlaylistEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please click the &quot;Open&quot; button at the bottom right to load the playlist. 的本地化字符串。
        /// </summary>
        public static string PlaylistOpened {
            get {
                return ResourceManager.GetString("PlaylistOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlist Options 的本地化字符串。
        /// </summary>
        public static string PlaylistOptions {
            get {
                return ResourceManager.GetString("PlaylistOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlist saved. 的本地化字符串。
        /// </summary>
        public static string PlaylistSaved {
            get {
                return ResourceManager.GetString("PlaylistSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single play duration time 的本地化字符串。
        /// </summary>
        public static string PlaylistSinglePlayDurationTime {
            get {
                return ResourceManager.GetString("PlaylistSinglePlayDurationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single play interval time 的本地化字符串。
        /// </summary>
        public static string PlaylistSinglePlayIntervalTime {
            get {
                return ResourceManager.GetString("PlaylistSinglePlayIntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time 的本地化字符串。
        /// </summary>
        public static string PlaylistStartTime {
            get {
                return ResourceManager.GetString("PlaylistStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total play duration time 的本地化字符串。
        /// </summary>
        public static string PlaylistTotalPlayDurationTime {
            get {
                return ResourceManager.GetString("PlaylistTotalPlayDurationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save playlist 的本地化字符串。
        /// </summary>
        public static string SavePlaylist {
            get {
                return ResourceManager.GetString("SavePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Librame Player. 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string WindowClose {
            get {
                return ResourceManager.GetString("WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize 的本地化字符串。
        /// </summary>
        public static string WindowMaximize {
            get {
                return ResourceManager.GetString("WindowMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string WindowRestore {
            get {
                return ResourceManager.GetString("WindowRestore", resourceCulture);
            }
        }
    }
}
